language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2

before_script:
    - composer update --prefer-dist --no-interaction

script:
    - php vendor/bin/phpunit tests/Unit
    - php vendor/bin/phpcs ./src ./tests

after_success:
    - bash <(curl -s https://codecov.io/bash)
